apiVersion: v1
kind: Pod

metadata:
  name: memory-oom-test

spec:
  restartPolicy: Never

  containers:
    - name: memory-test-container
      image: python:3.12-alpine

      resources:
        requests:
          memory: 25Mi
        limits:
          memory: 50Mi

      command:
        - python
        - -c
        - |
          import time
          print("Allocating 100 MiB...")
          data = bytearray(100 * 1024 * 1024)
          time.sleep(300)